[build]
  base = "."
  command = "yarn --cwd packages/ui buildSite"
  publish = "packages/ui/dist"

[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "18.20.4"
  YARN_VERSION = "1.22.22"
  PYTHON_VERSION = "3.10.14"
